// ------------------------------
// generate-exports — package metadata, not a build step
// ------------------------------
// Consumers never run this. It regenerates three files that would otherwise be
// hand-maintained lists of the same directory tree:
//
//   package.json "exports"   — short subpaths (@platformdesign/components/pl-button)
//   Library/index.mjs        — the "register everything" barrel
//   public/js/nav.data.mjs   — the documentation sidebar
//
// The sidebar is generated for the same reason as the others: it's meant to
// mirror Library/components/ exactly, and the only way to guarantee that is to
// read the directory rather than describe it twice.
//
// The category path (@platformdesign/components/app/inputs/pl-button) needs no
// generation — the "./*" pattern in package.json already serves it. The short
// names are explicit entries because an exports pattern can only carry one "*",
// and short name -> nested path isn't expressible as one substitution.
//
// Only directories with a NON-EMPTY index.mjs are included, so the 40-odd
// scaffolded-but-unwritten component folders don't become broken exports.
//
// Run: npm run exports

import { readdir, readFile, writeFile, stat } from 'node:fs/promises';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const COMPONENTS = join(ROOT, 'Library', 'components');

// Fixed entries, in resolution order. Explicit keys win over the "./*" pattern,
// so the generated short names slot in ahead of it.
const STATIC_EXPORTS = {
    '.': './Library/index.mjs',
    './tokens.css': './Library/_core/styles/tokens.css',
    './_core/*': './Library/_core/*',
    './utilities/*': './Library/utilities/*',
};

const PATTERN_EXPORTS = {
    './*': './Library/components/*/index.mjs',
};

/**
 * Every `<surface>/<group>/<tag>/` directory, flagged `written` when its
 * index.mjs actually has content. The unwritten ones are scaffolding — they
 * stay out of the package exports but still appear in the docs sidebar, so the
 * map of the system is honest about what exists yet.
 */
async function findComponents() {
    const found = [];

    for (const surface of await readdir(COMPONENTS)) {                 // app | content
        const surfaceDir = join(COMPONENTS, surface);
        if (!(await stat(surfaceDir)).isDirectory()) continue;

        for (const group of await readdir(surfaceDir)) {               // inputs | ui | …
            const groupDir = join(surfaceDir, group);
            if (!(await stat(groupDir)).isDirectory()) continue;

            for (const tag of await readdir(groupDir)) {               // pl-button
                const tagDir = join(groupDir, tag);
                if (!(await stat(tagDir)).isDirectory()) continue;

                // A missing OR empty index.mjs both mean "scaffolded, not
                // written yet" — the directory exists, the component doesn't.
                const entry = join(tagDir, 'index.mjs');
                const size = await stat(entry).then(s => s.size).catch(() => 0);

                found.push({
                    tag,
                    surface,
                    group,
                    written: size > 0,
                    path: './' + relative(ROOT, entry).split(/[\\/]/).join('/'),
                });
            }
        }
    }

    return found.sort((a, b) => a.tag.localeCompare(b.tag));
}

/** The exported class name in a component's index.mjs (`export class Button`). */
async function exportedClass(entry) {
    const source = await readFile(join(ROOT, entry.path), 'utf8');
    return source.match(/export\s+class\s+(\w+)/)?.[1] ?? null;
}

const all = await findComponents();
const components = all.filter(c => c.written);

// ------------------------------
// package.json
// ------------------------------
const pkgPath = join(ROOT, 'package.json');
const pkg = JSON.parse(await readFile(pkgPath, 'utf8'));

pkg.exports = {
    ...STATIC_EXPORTS,
    ...Object.fromEntries(components.map(c => [`./${c.tag}`, c.path])),
    ...PATTERN_EXPORTS,
};

await writeFile(pkgPath, JSON.stringify(pkg, null, 2) + '\n');

// ------------------------------
// Library/index.mjs
// ------------------------------
const named = await Promise.all(components.map(async c => ({ ...c, className: await exportedClass(c) })));

const lines = [
    '// ------------------------------',
    '// Platform Components — full barrel',
    '// ------------------------------',
    '// GENERATED by scripts/generate-exports.mjs — do not edit by hand.',
    '//',
    '// Importing this registers EVERY component as a side effect:',
    "//   import '@platformdesign/components';",
    '//',
    '// To ship less, import only what you use — each module registers just itself:',
    "//   import '@platformdesign/components/pl-button';",
    '//',
    '// Classes are re-exported for subclassing and instanceof checks.',
    '',
    ...named.map(c => `import './${relative(join(ROOT, 'Library'), join(ROOT, c.path)).split(/[\\/]/).join('/')}';`),
    '',
    ...named
        .filter(c => c.className)
        .map(c => `export { ${c.className} } from './${relative(join(ROOT, 'Library'), join(ROOT, c.path)).split(/[\\/]/).join('/')}';`),
    '',
];

await writeFile(join(ROOT, 'Library', 'index.mjs'), lines.join('\n'));

// ------------------------------
// public/js/nav.data.mjs — the docs sidebar
// ------------------------------
// Grouped surface -> group -> components, preserving the directory shape.
const tree = [];
for (const c of all) {
    let surface = tree.find(s => s.name === c.surface);
    if (!surface) tree.push(surface = { name: c.surface, groups: [] });

    let group = surface.groups.find(g => g.name === c.group);
    if (!group) surface.groups.push(group = { name: c.group, components: [] });

    group.components.push({ tag: c.tag, status: c.written ? 'ready' : 'planned' });
}

const navSource = `// ------------------------------
// Documentation navigation
// ------------------------------
// GENERATED by scripts/generate-exports.mjs — do not edit by hand.
// Mirrors Library/components/ exactly: surface -> group -> component.
// \`status\` is 'ready' when the component has a written index.mjs, and
// 'planned' when the directory is still scaffolding.

export const NAV = ${JSON.stringify(tree, null, 4)};
`;

await writeFile(join(ROOT, 'public', 'js', 'nav.data.mjs'), navSource);

console.log(`Exported ${components.length} of ${all.length} component(s):`);
for (const c of named) console.log(`  ${c.tag.padEnd(20)} ${c.surface}/${c.group}${c.className ? `  (${c.className})` : ''}`);
console.log(`Sidebar: ${all.length} entries across ${tree.length} surface(s).`);
